package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t");

		String openId = request.getParameter("openId");
		System.out.println(openId);
		if(null == openId){
			openId="";
		}

	
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no\" />\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n");
      out.write("\t<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\n");
      out.write("    <title></title>\n");
      out.write("    <script src=\"js/mui.min.js\"></script>\n");
      out.write("    <script src=\"js/mui.picker.js\"></script>\n");
      out.write("\t<script src=\"js/mui.poppicker.js\"></script>\n");
      out.write("    <script src=\"js/mui.picker.min.js\"></script>\n");
      out.write("    <script src=\"js/jquery-1.11.1.min.js\"></script>\n");
      out.write("    <!--<script src=\"js/scale.js\"></script>-->\n");
      out.write("    <script src=\"js/views/ajaxData.js\"></script>\n");
      out.write("    \n");
      out.write("    <link href=\"css/mui.min.css\" rel=\"stylesheet\"/>\n");
      out.write("    <!--App自定义的css-->\n");
      out.write("\t<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/app.css\" />-->\n");
      out.write("\t<link href=\"css/mui.picker.css\" rel=\"stylesheet\" />\n");
      out.write("\t<link href=\"css/mui.poppicker.css\" rel=\"stylesheet\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/mui.picker.min.css\" />\n");
      out.write("    <link href=\"css/iconfont.css\" rel=\"stylesheet\"/>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\"/>\n");
      out.write("    <style> \n");
      out.write("\t\t.mui-control-content {\n");
      out.write("\t\t\tbackground-color: white;\n");
      out.write("\t\t\tmin-height: 500px;\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<input type=\"hidden\" name=\"openId\" id=\"openId\" value=\"");
      out.print(openId);
      out.write("\">\n");
      out.write("<input type=\"hidden\" name=\"user_id\" id=\"user_id\" value=\"\">\n");
      out.write("\t<header class=\"mui-bar mui-bar-nav\">\n");
      out.write("\t    <a class=\"mui-action-back mui-icon mui-icon-left-nav mui-pull-left title-back\">返回</a>\n");
      out.write("\t    <h1 class=\"mui-title\" >一键安装</h1>\n");
      out.write("\t  <!--  <a id=\"maintence\" class=\"mui-icon mui-icon-more icon-mark mui-pull-right\"></a> -->  \n");
      out.write("\t</header>\n");
      out.write("\t<nav class=\"mui-bar mui-bar-tab\">\n");
      out.write("\t\t<div style=\"width:80%;margin:0 auto\">    \n");
      out.write("\t    \t<button id=\"add\" type=\"button\" class=\"mui-btn mui-btn-primary\" style=\"width:100%;background-color: #32beff;border:0\">立即提交</button>\n");
      out.write("\t   </div>\n");
      out.write("\t</nav>\n");
      out.write("\t<div class=\"mui-content\">\n");
      out.write("\t\t\t<div id=\"slider\" class=\"mui-slider\">\n");
      out.write("\t\t\t\t<div id=\"sliderSegmentedControl\" class=\"mui-slider-indicator mui-segmented-control mui-segmented-control-inverted\">\n");
      out.write("\t\t\t\t\t<a class=\"mui-control-item  mui-active\" href=\"#item1mobile\" style=\"color:#32BEFF;\">\n");
      out.write("\t\t\t\t\t\t新机报装\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<!--\n");
      out.write("                    <a class=\"mui-control-item\" href=\"#item2mobile\">\n");
      out.write("\t\t\t\t\t\t移机报装\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("                    -->\n");
      out.write("\t\t\t\t\t<div class=\"mui-control-item\" style=\"color:#CCCCCC;\" disabled=\"disabled\" readonly>\n");
      out.write("\t\t\t\t\t\t移机报装\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"sliderProgressBar\" class=\"mui-slider-progress-bar mui-col-xs-6\"></div>\n");
      out.write("\t\t\t\t<div class=\"mui-slider-group\">\n");
      out.write("\t\t\t\t\t<div id=\"item1mobile\" class=\"mui-slider-item mui-control-content mui-active\">\n");
      out.write("\t\t\t\t\t\t<div id=\"scroll1\" class=\"mui-scroll-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mui-scroll\" style=\"height:760px;position:absolute;overflow-y :auto;\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--<div style=\"height:80px;border-bottom: 1px solid #dcdcdc;line-height: 80px;padding-left:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"color1\">我的产品</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a style=\"display: block;background:url(images/arrow-right.png) no-repeat;background-size:6px 12px;width:12px;height:24px;float:right;margin-top:28px;margin-right:30px\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>-->\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;border-bottom: 1px solid #dcdcdc;padding-left:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px\"><span class=\"triangle\">*</span><span class=\"color1\">产品品牌</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:50px;float: left;padding-right:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"pinpai\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"pinpai-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px\"><span class=\"triangle\">*</span><span class=\"color1\">产品大类</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:50px;float: left;border-bottom: 1px solid #dcdcdc;padding-right:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"type1\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"type1-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px;\"><span class=\"triangle\">*</span><span class=\"color1\">产品子类</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:50px;float: left;padding-right:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"type2\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"type2-hidden\" name=\"product_id\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px\"><span class=\"triangle\">*</span><span class=\"color1\">联系人</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:50px;float: left;padding-right:30px\">\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"contact\" name=\"contact_name\" placeholder=\"请输入\" class=\"color2\" style=\"padding:0;margin:0;line-height:50px;height:50px;border:0;background: transparent;font-size:14px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px\"><span class=\"triangle\">*</span><span class=\"color1\">联系电话</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:50px;float: left;padding-right:30px\">\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"number\" id=\"phone\" name=\"mobile_phone\" placeholder=\"请输入\" class=\"color2\" style=\"padding:0;margin:0;line-height:50px;height:50px;border:0;background: transparent;font-size:14px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"phone-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px\"><span class=\"triangle\">*</span><span class=\"color1\">服务地址</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:50px;float: left;border-bottom: 1px solid #dcdcdc;padding-right:32px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"Address\" name=\"Address_name\" placeholder=\"请输入\" class=\"color2\" style=\"padding:0;margin:0;line-height:50px;height:50px;border:0;background: transparent;font-size:14px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:50px;float:left;padding-top:15px;text-align: right;border-bottom: 1px solid #dcdcdc;\"><span class=\"color1\">省</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:50px;float: left;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"sheng\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"sheng-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:50px;float: left;border-bottom: 1px solid #dcdcdc;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:50px;float:left;padding-top:15px;border-bottom: 1px solid #dcdcdc;\"><span class=\"color1\">市</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:50px;float: left;padding-right:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"shi\" class=\"color3\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"shi-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:50px;float:left;padding-top:15px;text-align: right;border-bottom: 1px solid #dcdcdc;\"><span class=\"color1\">区</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:70%;height:50px;float: left;padding-right:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"area\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"area-hidden\" name=\"district\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;padding-left:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:50px;float:left;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"infoaddress\" class=\"color2\" placeholder=\"请填写详细地址\" style=\"padding:0;margin:0;height:40px;border:0;background: transparent;font-size:14px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"infoaddress-hidden\" name=\"address\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px;\"><span class=\"triangle\">*</span><span class=\"color1\">预约日期</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:50px;float: left;padding-right:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"newdate\" class=\"color2 dates\" data-options='{\"type\":\"date\"}' style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"newdate-hidden\" name=\"require_service_date\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<!--<div style=\"width:100%;height:50px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px;\"><span class=\"triangle\">*</span><span class=\"color1\">预约时间</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:35%;height:50px;float: left;padding-right:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"newdate-font\" class=\"color2 dates\" data-options='{\"type\":\"hour\"}' style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"newdate-font-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"color1\" style=\"width:5%;height:50px;float: left;text-align: right;padding-top:15px;\">到</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:35%;height:50px;float: left;padding-right:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"newdate-after\" class=\"color2 dates\" data-options='{\"type\":\"hour\"}' style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"newdate-after-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"newdate-front-after-hidden\" name=\"service_time\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t</div>-->\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:50px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:50px;float:left;padding-top:15px;\"><span class=\"triangle\">*</span><span class=\"color1\">预约时间</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:50px;float: left;padding-right:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"newdate-front-after\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:50px;width:100%;height:50px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"newdate-front-after-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<!--<div style=\"width:100%;height:40px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"color3\" style=\"width:25%;height:40px;float: left;text-align: right;padding-top:10px;\">到</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:40px;float: left;padding-right:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"newdate-after\" class=\"color3 dates\" data-options='{\"type\":\"hour\"}' style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"newdate-after-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"newdate-front-after-hidden\" name=\"service_time\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t</div>-->\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"require_service_desc\" value=\"hardcode\">\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"service_type\" value=\"T02\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div id=\"item2mobile\" class=\"mui-slider-item mui-control-content\">\n");
      out.write("\t\t\t\t\t\t<div id=\"scroll2\" class=\"mui-scroll-wrapper\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mui-scroll\" style=\"height:760px;position:absolute;overflow-y :auto;\">\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"height:80px;border-bottom: 1px solid #dcdcdc;line-height: 80px;padding-left:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"color1\">我的产品</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t<a style=\"display: block;background:url(images/arrow-right.png) no-repeat;background-size:6px 12px;width:12px;height:24px;float:right;margin-top:28px;margin-right:30px\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:40px;border-bottom: 1px solid #dcdcdc;padding-left:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px\"><span class=\"triangle\">*</span><span class=\"color1\">品牌</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:40px;float: left;padding-right:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-pinpai\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-pinpai-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:80px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px\"><span class=\"triangle\">*</span><span class=\"color1\">类型</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:40px;float: left;border-bottom: 1px solid #dcdcdc;padding-right:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-type1\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-type1-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:40px;float: left;padding-right:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-type2\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-type2-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:40px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px\"><span class=\"triangle\">*</span><span class=\"color1\">联系人</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:40px;float: left;padding-right:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-contact\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;font-size:14px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-contact-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:40px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px\"><span class=\"triangle\">*</span><span class=\"color1\">联系电话</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:40px;float: left;padding-right:30px\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"number\" name=\"yjbz-phone\" id=\"yjbz-phone\" placeholder=\"请输入\" class=\"color2\" style=\"padding:0;margin:0;height:40px;border:0;background: transparent;font-size:14px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-phone-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:60px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:60px;float:left;padding-top:20px\"><span class=\"triangle\">*</span><span class=\"color1\">旧地址</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:45%;height:60px;float: left;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-Address\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:60px;width:100%;height:60px;font-size:14px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-Address-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:60px;float: left;border-bottom: 1px solid #dcdcdc;padding-right:30px;text-align: right;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a id=\"yjbz-icon-add\" class=\"mui-icon iconfont icon-roundaddfill\" style=\"font-size: 30px;color: #32beff;padding-top: 15px;margin:0\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:40px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float:left;padding-top:10px;text-align: right;border-bottom: 1px solid #dcdcdc;\"><span class=\"color1\">省</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:40px;float: left;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-sheng\" class=\"color3\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-sheng-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float: left;border-bottom: 1px solid #dcdcdc;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float:left;padding-top:10px;border-bottom: 1px solid #dcdcdc;\"><span class=\"color1\">市</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:40px;float: left;padding-right:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-shi\" class=\"color3\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-shi-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:40px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float:left;padding-top:10px;text-align: right;border-bottom: 1px solid #dcdcdc;\"><span class=\"color1\">区</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:70%;height:40px;float: left;padding-right:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-area\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-area-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:40px;padding-left:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:40px;float:left;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"yjbz-infoaddress\" class=\"color2\" placeholder=\"请填写详细地址\" style=\"padding:0;margin:0;height:40px;border:0;background: transparent;font-size:14px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:60px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:60px;float:left;padding-top:20px\"><span class=\"triangle\">*</span><span class=\"color1\">新地址</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:45%;height:60px;float: left;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-newAddress\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:60px;width:100%;height:60px;font-size:14px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-newAddress-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:60px;float: left;border-bottom: 1px solid #dcdcdc;padding-right:30px;text-align: right;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a id=\"icon-newadd\" class=\"mui-icon iconfont icon-roundaddfill\" style=\"font-size: 30px;color: #32beff;padding-top: 15px;margin:0\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:40px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float:left;padding-top:10px;text-align: right;border-bottom: 1px solid #dcdcdc;\"><span class=\"color1\">省</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:40px;float: left;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-newsheng\" class=\"color3\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-newsheng-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float: left;border-bottom: 1px solid #dcdcdc;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float:left;padding-top:10px;border-bottom: 1px solid #dcdcdc;\"><span class=\"color1\">市</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:40px;float: left;padding-right:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-newshi\" class=\"color3\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-newshi-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:40px;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float:left;padding-top:10px;text-align: right;border-bottom: 1px solid #dcdcdc;\"><span class=\"color1\">区</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:70%;height:40px;float: left;padding-right:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-newarea\" class=\"color2\" style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-newarea-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:40px;padding-left:30px;border-bottom: 1px solid #dcdcdc;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:75%;height:40px;float:left;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-newinfoaddress\" type=\"text\" class=\"color2\" placeholder=\"请填写详细地址\" style=\"padding:0;margin:0;height:40px;border:0;background: transparent;font-size:14px;\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width:100%;height:60px;border-bottom: 1px solid #dcdcdc;padding-left:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:25%;height:40px;float:left;padding-top:10px;\"><span class=\"triangle\">*</span><span class=\"color1\">预约日期</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float:left;padding-top:10px;text-align: right;\"><span class=\"color1\">日</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:40px;float: left;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-newdate\" class=\"color3 dates\" data-options='{\"type\":\"date\"}' style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-newdate-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float: left;\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:5%;height:40px;float:left;padding-top:10px;\"><span class=\"color1\">时</span></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div style=\"width:30%;height:40px;float: left;padding-right:30px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"yjbz-newtime\" class=\"color3 dates\" data-options='{\"type\":\"time\"}' style=\"background:url(images/arrow-down.png) right center no-repeat;background-size:12px 6px;border:0;line-height:40px;width:100%;height:40px;padding-left: 5px;\">请输入</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"yjbz-newtime-hidden\" type=\"hidden\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\tvar userPicker;\n");
      out.write("\t\t\t(function($, doc) {\n");
      out.write("\t\t\t\tmui.init({\n");
      out.write("\t\t\t\t\tswipeBack: false\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t$('.mui-scroll-wrapper').scroll({\n");
      out.write("\t\t\t\t\tindicators: true //是否显示滚动条\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t/*var html2 = '<ul class=\"mui-table-view\"><li class=\"mui-table-view-cell\">第二个选项卡子项-1</li><li class=\"mui-table-view-cell\">第二个选项卡子项-2</li><li class=\"mui-table-view-cell\">第二个选项卡子项-3</li><li class=\"mui-table-view-cell\">第二个选项卡子项-4</li><li class=\"mui-table-view-cell\">第二个选项卡子项-5</li></ul>';\n");
      out.write("\t\t\t\tvar item2 = document.getElementById('item2mobile');\n");
      out.write("\t\t\t\tdocument.getElementById('slider').addEventListener('slide', function(e) { \n");
      out.write("\t\t\t\t\tif (e.detail.slideNumber === 1) {\n");
      out.write("\t\t\t\t\t\tif (item2.querySelector('.mui-loading')) {\n");
      out.write("\t\t\t\t\t\t\tsetTimeout(function() {\n");
      out.write("\t\t\t\t\t\t\t\titem2.querySelector('.mui-scroll').innerHTML = html2;\n");
      out.write("\t\t\t\t\t\t\t}, 500);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});*/\n");
      out.write("\t\t\t\t$.ready(function() {\n");
      out.write("\t\t\t\t\t//普通示例\n");
      out.write("\t\t\t\t\tuserPicker = new $.PopPicker();\n");
      out.write("\t\t\t\t\tvar pinpai = doc.getElementById('pinpai');\n");
      out.write("\t\t\t\t\tpinpai.addEventListener('tap', function(event) {\n");
      out.write("\t\t\t\t\t\tajax_pinpai_Data(this);\n");
      out.write("\t\t\t\t\t}, false);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar type1 = doc.getElementById('type1');\n");
      out.write("\t\t\t\t\ttype1.addEventListener('tap', function(event) {\n");
      out.write("\t\t\t\t\t\tajax_type1_Data(this);\n");
      out.write("\t\t\t\t\t}, false);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar type2 = doc.getElementById('type2');\n");
      out.write("\t\t\t\t\ttype2.addEventListener('tap', function(event) {\n");
      out.write("\t\t\t\t\t\tajax_type2_Data(this);\n");
      out.write("\t\t\t\t\t}, false);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar sheng = doc.getElementById('sheng');\n");
      out.write("\t\t\t\t\tsheng.addEventListener('tap', function(event) {\n");
      out.write("\t\t\t\t\t\tajax_area_Data(this);\n");
      out.write("\t\t\t\t\t}, false);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar shi = doc.getElementById('shi');\n");
      out.write("\t\t\t\t\tshi.addEventListener('tap', function(event) {\n");
      out.write("\t\t\t\t\t\tvar sheng_hidden = doc.getElementById(\"sheng-hidden\");\n");
      out.write("\t\t\t\t\t\tajax_shi_Data(this,sheng_hidden.value);\n");
      out.write("\t\t\t\t\t}, false);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar areaa = doc.getElementById('area');\n");
      out.write("\t\t\t\t\tareaa.addEventListener('tap', function(event) {\n");
      out.write("\t\t\t\t\t\tvar sheng_hidden = doc.getElementById(\"sheng-hidden\");\n");
      out.write("\t\t\t\t\t\tvar shi_hidden = doc.getElementById(\"shi-hidden\");\n");
      out.write("\t\t\t\t\t\tajax_areaa_Data(this,sheng_hidden.value,shi_hidden.value);\n");
      out.write("\t\t\t\t\t}, false);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar newdate = doc.getElementById('newdate-front-after');\n");
      out.write("\t\t\t\t\tnewdate.addEventListener('tap', function(event) {\n");
      out.write("\t\t\t\t\t\tajax_time_Data(this);\n");
      out.write("\t\t\t\t\t}, false);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\n");
      out.write("\t\t\t\t//跳转新页面\n");
      out.write("\t\t\t\t/*document.getElementById('maintence').addEventListener('tap',function(){\n");
      out.write("\t\t\t\t\tmui.openWindow({\n");
      out.write("\t\t\t\t\t    url: 'pages/maintence.html',\n");
      out.write("\t\t\t\t\t    id: 'maintence',\n");
      out.write("\n");
      out.write("\t\t\t\t\t    extras: {\n");
      out.write("\t\t\t\t\t       //自定义扩展参数，可以用来处理页面间传值\n");
      out.write("\t\t\t\t\t    }\n");
      out.write("\t\t\t\t\t    \n");
      out.write("\t\t\t\t\t})\n");
      out.write("\t\t\t\t})*/\n");
      out.write("\t\t\t\tdocument.getElementById('add').addEventListener('tap',function(){\n");
      out.write("\t\t\t\t\taddData();\n");
      out.write("\t\t\t\t})\n");
      out.write("\t\t\t\tvar btns = $('.dates');\n");
      out.write("\t\t\t\tbtns.each(function(i, btn) {\n");
      out.write("\t\t\t\t\tbtn.addEventListener('tap', function() {\n");
      out.write("\t\t\t\t\t\tvar obj = this;  \n");
      out.write("\t\t\t\t\t\tvar optionsJson = this.getAttribute('data-options') || '{}';\n");
      out.write("\t\t\t\t\t\tvar options = JSON.parse(optionsJson);\n");
      out.write("\t\t\t\t\t\tvar id = this.getAttribute('id');\n");
      out.write("\t\t\t\t\t\t/*\n");
      out.write("\t\t\t\t\t\t * 首次显示时实例化组件\n");
      out.write("\t\t\t\t\t\t * 示例为了简洁，将 options 放在了按钮的 dom 上\n");
      out.write("\t\t\t\t\t\t * 也可以直接通过代码声明 optinos 用于实例化 DtPicker\n");
      out.write("\t\t\t\t\t\t */\n");
      out.write("\t\t\t\t\t\tvar picker = new $.DtPicker(options);\n");
      out.write("\t\t\t\t\t\tpicker.show(function(rs) {\n");
      out.write("\t\t\t\t\t\t\t/*\n");
      out.write("\t\t\t\t\t\t\t * rs.value 拼合后的 value\n");
      out.write("\t\t\t\t\t\t\t * rs.text 拼合后的 text\n");
      out.write("\t\t\t\t\t\t\t * rs.y 年，可以通过 rs.y.vaue 和 rs.y.text 获取值和文本\n");
      out.write("\t\t\t\t\t\t\t * rs.m 月，用法同年\n");
      out.write("\t\t\t\t\t\t\t * rs.d 日，用法同年\n");
      out.write("\t\t\t\t\t\t\t * rs.h 时，用法同年\n");
      out.write("\t\t\t\t\t\t\t * rs.i 分（minutes 的第二个字母），用法同年\n");
      out.write("\t\t\t\t\t\t\t */\n");
      out.write("\t\t\t\t\t\t\tif(obj.getAttribute(\"id\") == \"newdate\"){\n");
      out.write("\t\t\t\t\t\t\t\tdoc.getElementById(\"newdate\").innerText = rs.y.text+\"-\"+rs.m.text+\"-\"+rs.d.text;\n");
      out.write("\t\t\t\t\t\t\t\tdoc.getElementById(\"newdate-hidden\").value = rs.y.text+\"-\"+rs.m.text+\"-\"+rs.d.text;\n");
      out.write("\t\t\t\t\t\t\t}else if(obj.getAttribute(\"id\") == \"newdate-font\"){\n");
      out.write("\t\t\t\t\t\t\t\tdoc.getElementById(\"newdate-font\").innerText = rs.h.text+\":00\";\n");
      out.write("\t\t\t\t\t\t\t\tdoc.getElementById(\"newdate-font-hidden\").value = rs.h.text+\":00\";\n");
      out.write("\t\t\t\t\t\t\t}else if(obj.getAttribute(\"id\") == \"newdate-after\"){\n");
      out.write("\t\t\t\t\t\t\t\tdoc.getElementById(\"newdate-after\").innerText = rs.h.text+\":00\";\n");
      out.write("\t\t\t\t\t\t\t\tdoc.getElementById(\"newdate-after-hidden\").value = rs.h.text+\":00\";\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t//doc.getElementById(\"newdate-hidden\").innerText = rs.value;\n");
      out.write("\t\t\t\t\t\t\t//alert(rs.value);\n");
      out.write("\t\t\t\t\t\t\t/* \n");
      out.write("\t\t\t\t\t\t\t * 返回 false 可以阻止选择框的关闭\n");
      out.write("\t\t\t\t\t\t\t * return false;\n");
      out.write("\t\t\t\t\t\t\t */\n");
      out.write("\t\t\t\t\t\t\t/*\n");
      out.write("\t\t\t\t\t\t\t * 释放组件资源，释放后将将不能再操作组件\n");
      out.write("\t\t\t\t\t\t\t * 通常情况下，不需要示放组件，new DtPicker(options) 后，可以一直使用。\n");
      out.write("\t\t\t\t\t\t\t * 当前示例，因为内容较多，如不进行资原释放，在某些设备上会较慢。\n");
      out.write("\t\t\t\t\t\t\t * 所以每次用完便立即调用 dispose 进行释放，下次用时再创建新实例。\n");
      out.write("\t\t\t\t\t\t\t */\n");
      out.write("\t\t\t\t\t\t\t//picker.dispose();\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t}, false);\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t})(mui, document);\n");
      out.write("\t\t\t\n");
      out.write("\t\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
